/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lf_pcg_Pcg */

#ifndef _Included_org_lf_pcg_Pcg
#define _Included_org_lf_pcg_Pcg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultMultiplier8
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_getDefaultMultiplier8
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultMultiplier16
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_getDefaultMultiplier16
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultMultiplier32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_getDefaultMultiplier32
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultMultiplier64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_getDefaultMultiplier64
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultIncrement8
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_getDefaultIncrement8
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultIncrement16
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_getDefaultIncrement16
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultIncrement32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_getDefaultIncrement32
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    getDefaultIncrement64
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_getDefaultIncrement64
  (JNIEnv *, jclass);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_8_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;B)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_18_1srandom
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_8_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;B)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_18_1srandom
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_8_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;B)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_18_1srandom
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_8_srandom
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState8;BB)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_18_1srandom
  (JNIEnv *, jclass, jobject, jbyte, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;S)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1srandom
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;S)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_116_1srandom
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;S)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_116_1srandom
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_srandom
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;SS)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_116_1srandom
  (JNIEnv *, jclass, jobject, jshort, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1srandom
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_132_1srandom
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_132_1srandom
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_srandom
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;II)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_132_1srandom
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1srandom
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_164_1srandom
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_srandom
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_164_1srandom
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_srandom
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;JJ)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_164_1srandom
  (JNIEnv *, jclass, jobject, jlong, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_8_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_18_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_8_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_18_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_8_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_18_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_8_step
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState8;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_18_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_116_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_116_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_step
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_116_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_132_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_132_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_step
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_132_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_164_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_step
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_164_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_step
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_164_1step
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_8_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_18_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_8_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_18_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_8_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_18_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_8_advance
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState8;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_18_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_116_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_116_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_advance
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_116_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_132_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_132_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_advance
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_132_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_mcg_164_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_advance
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_unique_164_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_advance
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;I)V
 */
JNIEXPORT void JNICALL Java_org_lf_pcg_Pcg_setseq_164_1advance
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_xsh_rs_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1xsh_1rs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_xsh_rs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1xsh_1rs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_xsh_rs_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1xsh_1rs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_xsh_rs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1xsh_1rs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsh_rs_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsh_1rs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsh_rs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsh_1rs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_xsh_rs_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_unique_116_1xsh_1rs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_xsh_rs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_unique_116_1xsh_1rs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_xsh_rs_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_132_1xsh_1rs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_xsh_rs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_132_1xsh_1rs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsh_rs_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsh_1rs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsh_rs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsh_1rs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_xsh_rs_8_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_116_1xsh_1rs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_xsh_rs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_116_1xsh_1rs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_xsh_rs_16_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_132_1xsh_1rs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_xsh_rs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_132_1xsh_1rs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsh_rs_32_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsh_1rs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsh_rs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsh_1rs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_xsh_rs_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_mcg_116_1xsh_1rs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_xsh_rs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_mcg_116_1xsh_1rs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_xsh_rs_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_mcg_132_1xsh_1rs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_xsh_rs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_mcg_132_1xsh_1rs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsh_rs_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsh_1rs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsh_rs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsh_1rs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_xsh_rr_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1xsh_1rr_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_xsh_rr_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1xsh_1rr_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_xsh_rr_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1xsh_1rr_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_xsh_rr_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1xsh_1rr_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsh_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsh_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsh_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsh_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_xsh_rr_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_unique_116_1xsh_1rr_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_xsh_rr_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_unique_116_1xsh_1rr_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_xsh_rr_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_132_1xsh_1rr_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_xsh_rr_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_132_1xsh_1rr_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsh_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsh_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsh_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsh_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_xsh_rr_8_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_116_1xsh_1rr_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_xsh_rr_8_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_116_1xsh_1rr_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_xsh_rr_16_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_132_1xsh_1rr_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_xsh_rr_16_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_132_1xsh_1rr_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsh_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsh_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsh_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsh_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_xsh_rr_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_mcg_116_1xsh_1rr_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_16_xsh_rr_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_mcg_116_1xsh_1rr_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_xsh_rr_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_mcg_132_1xsh_1rr_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_32_xsh_rr_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_mcg_132_1xsh_1rr_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsh_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsh_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsh_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsh_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_8_rxs_m_xs_8_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_18_1rxs_1m_1xs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_8_rxs_m_xs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState8;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_oneseq_18_1rxs_1m_1xs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_rxs_m_xs_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1rxs_1m_1xs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_16_rxs_m_xs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_oneseq_116_1rxs_1m_1xs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_rxs_m_xs_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1rxs_1m_1xs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_32_rxs_m_xs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_132_1rxs_1m_1xs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_rxs_m_xs_64_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1rxs_1m_1xs_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_rxs_m_xs_64_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1rxs_1m_1xs_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_rxs_m_xs_16_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_116_1rxs_1m_1xs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_16_rxs_m_xs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState16;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_unique_116_1rxs_1m_1xs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_rxs_m_xs_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_132_1rxs_1m_1xs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_32_rxs_m_xs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState32;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_132_1rxs_1m_1xs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_rxs_m_xs_64_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_unique_164_1rxs_1m_1xs_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_rxs_m_xs_64_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_unique_164_1rxs_1m_1xs_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_8_rxs_m_xs_8_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState8;)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_18_1rxs_1m_1xs_18_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_8_rxs_m_xs_8_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState8;B)B
 */
JNIEXPORT jbyte JNICALL Java_org_lf_pcg_Pcg_setseq_18_1rxs_1m_1xs_18_1bounded
  (JNIEnv *, jclass, jobject, jbyte);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_rxs_m_xs_16_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_116_1rxs_1m_1xs_116_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_16_rxs_m_xs_16_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState16;S)S
 */
JNIEXPORT jshort JNICALL Java_org_lf_pcg_Pcg_setseq_116_1rxs_1m_1xs_116_1bounded
  (JNIEnv *, jclass, jobject, jshort);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_rxs_m_xs_32_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_132_1rxs_1m_1xs_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_32_rxs_m_xs_32_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState32;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_132_1rxs_1m_1xs_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_rxs_m_xs_64_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_setseq_164_1rxs_1m_1xs_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_rxs_m_xs_64_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_setseq_164_1rxs_1m_1xs_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsl_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsl_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsl_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsl_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsl_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsl_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsl_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsl_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsl_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsl_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsl_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsl_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsl_rr_32_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsl_1rr_132_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    mcg_64_xsl_rr_32_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;I)I
 */
JNIEXPORT jint JNICALL Java_org_lf_pcg_Pcg_mcg_164_1xsl_1rr_132_1bounded
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsl_rr_rr_64_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsl_1rr_1rr_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    oneseq_64_xsl_rr_rr_64_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_oneseq_164_1xsl_1rr_1rr_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsl_rr_rr_64_random
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsl_1rr_1rr_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    unique_64_xsl_rr_rr_64_bounded
 * Signature: (Lorg/lf/pcg/PcgState/PcgState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_unique_164_1xsl_1rr_1rr_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsl_rr_rr_64_random
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsl_1rr_1rr_164_1random
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lf_pcg_Pcg
 * Method:    setseq_64_xsl_rr_rr_64_bounded
 * Signature: (Lorg/lf/pcg/PcgSetseqState/PcgSetseqState64;J)J
 */
JNIEXPORT jlong JNICALL Java_org_lf_pcg_Pcg_setseq_164_1xsl_1rr_1rr_164_1bounded
  (JNIEnv *, jclass, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
